---
- name: Play level variables example
  hosts_file:
  - hosts.yaml
  vars_files:
    - course.yaml
  tasks:
    - name: Print play level variables
      ansible.builtin.debug:
        msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"
